version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "monthly"
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Tokyo'
