queue_rules:
  - name: default
    queue_conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author=dependabot[bot]
      - status-success=ci (3.9)
      - status-success=ci (3.10)
      - status-success=ci (3.11)
      - status-success=ci (3.12)
      - status-success=ci (3.13)
    merge_conditions: []
    commit_message_template: |-
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: automatic merge of Dependabot PRs
    conditions: []
    actions:
      queue:
