SEQ_NUM = "SequenceNumber"
PARTITION_KEY = "PartitionKey"
DATA = "Data"
TIMESTAMP = "ApproximateArrivalTimestamp"
SHARD_ID = "ShardId"
NUM_OF_RECORDS = "NumOfRecords"
LAST_ADDED_TIME = "LastAddedTime"
NUMBER = "No"
