########################################################################
# format check, type check, Unit test, E2E test
########################################################################

name: ci-action
run-name: ${{ github.workflow }} workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
# 全パーミッションの無効化
permissions: {}
# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        # 複数のPythonバージョンで動作確認
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      # Bashトレーシングオプション
      - run: set -x

      # 前提情報の出力
      - run: cat $GITHUB_EVENT_PATH
      - run: lsb_release -d
      - run: gh --version
      - run: aws --version


      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity

      - name: setup python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd
        with:
          poetry-version: 1.8.4

      - name: install package
        run: poetry install --no-interaction --no-ansi

      - name: black check format
        run: poetry run poe format-check

      - name: mypy typecheck
        run: poetry run poe typecheck

      - name: unit test
        run: poetry run poe test-no-cov

      - name: E2E test
        run: poetry run poe test-e2e
